<?php

namespace Campsite\EventBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends EntityRepository
{

  /**
   * find Attendees
   * @param integer $eventId EventId
   * @return QueryBuilder
   */
  public function findAttendees($eventId=0)
  {
 
    $qb = $this->getEntityManager()->createQueryBuilder();
    $qb->select('u')
        ->from('Campsite\EventBundle\Entity\User', 'u')
        ->leftJoin('u.events','e')	
		    ->Where('e.id  =:eventId')			
		    ->setParameter('eventId', $eventId);
        //->orderBy('e.fromDate', 'DESC');
	 
    $query = $qb->getQuery();
    return $query->getResult();
  }
}